#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

mkdir -p /boot/docker-compose/02_backupfriend
pushd /boot/docker-compose/02_backupfriend
    wget https://raw.githubusercontent.com/guysoft/BackupFriend-docker/master/src/docker-compose.yml
    wget https://raw.githubusercontent.com/guysoft/BackupFriend-docker/master/src/rdw.conf
    wget https://raw.githubusercontent.com/guysoft/BackupFriend-docker/master/src/env_raspberrypi
    mv env_raspberrypi .env
popd

# Make an empty db file
mkdir -p /etc/rdiffweb
touch /etc/rdiffweb/rdw.db
chown "${BASE_USER}:${BASE_USER}" /etc/rdiffweb/rdw.db
chown "${BASE_USER}:${BASE_USER}" /etc/rdiffweb

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

# Make an empty file so when we start the container it does not create a folder
mkdir -p /etc/authorized_keys
touch /etc/authorized_keys/user
chmod 600 /etc/authorized_keys/user
chown "${BASE_USER}:${BASE_USER}" /etc/authorized_keys/user
chown "${BASE_USER}:${BASE_USER}" /etc/authorized_keys

# Make backup folder
mkdir /backup
chmod 777 /backup

# Link the auto-mount usb folder to the backups folder
ln -s /media /backup/media

systemctl enable backupfriend-startup.service

